### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by UltraHQ** [4d72526f626f74/MrRobot#2]
`[19.07.2023 20:43:18] MrRobot.lua: syntax error: [string "MrRobot.lua"]:14: unexpected symbol near 'Version mismatch some features may not work! Script version: {GTAO_VERSION} | GTAO version: {GAME_VERSION}'
    14 | util.toast($"Version mismatch some features may not work! Script version: {GTAO_VERSION} | GTAO version: {GAME_VERSION}")
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ here: unexpected symbol.
`

Already did clean reinstall of MrRobot

**Comment by 4d72526f626f74** [comment]
I know, whatever Stand did in the latest Pluto update caused that error to start appearing for people

**Comment by UltraHQ** [comment]
I just removed all "$" from all files and it worked again
